########################################################################
# Values section defines the parameters to the chart
# These are specific to the chart being installed
########################################################################

imagePullSecret: regcred
image:
  repository: container-registry.dev8.bip.va.gov/archetypetest/bip-archetypetest
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
consul:
  enabled: true
  scheme: http
  host: dev8-consul.vault.svc.dev8
  config:
    prefix: config/archetypetest
    enabled: true
  discovery:
    enabled: false
    register: false
spring:
  profiles: "dev, ci"
opa:
  enabled: true # OPAEnablement: Set this to true if you want to enable OPA
  rego: api_authz_jwt_token.rego
