scrape_configs:
  - job_name: 'app_metrics'

    consul_sd_configs:
    - server: 'consul:8500'
      scheme: 'http'
      token: '7652ba4c-0f6e-8e75-5724-5e083d72cfe4'
    
    relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex: 'consul'
      action: drop
    - source_labels: ['__meta_consul_service']
      target_label: 'service'
      replacement: '${1}'
      action: replace

    scrape_interval: 10s
    scheme: http
    metrics_path: /actuator/prometheus
  